### ISSUE TITLE
"Unknown package in top-level dependencies: <meteor_package_name>"

### ISSUE THREAD

**Issue by derek-fong** [Urigo/meteor-client-bundler#15]
Steps to reproduce: 
1. `mkdir api/packages`
2. Clone/copy any meteor package source files into `api/packages/<meteor_package_name>`
3. Run `meteor add <meteor_package_name>`
3. run `meteor-client bundle -s api` from project root.
4. Fail with error message `Unknown package in top-level dependencies: <meteor_package_name>`.

**Comment by derek-fong** [comment]
#7

**Comment by DAB0mB** [comment]
Just implemented an option to specify `packages` dir. I'm closing this issue
