### ISSUE TITLE
Question about config

### ISSUE THREAD

**Issue by AwsmOli** [Urigo/meteor-client-bundler#2]
Hey, 
im trying to use this with the accounts-facebook and accounts-google packages.

is there a method to find out which dependencies in which order i will need to specify as the imports?

Some dependencies will be needed by both, do i need to specify them for each plugin, or is one time enough?

**Comment by AwsmOli** [comment]
Okay i now just tried and errored me to get alle the dependencies to work, but now im stuck with:

> Runtime Error
> Cannot read property 'innerHTML' of null

at

`var config = JSON.parse(document.getElementById("config").innerHTML);`

which is line 3 of `packages/oauth/end_of_popup_response.js`


Where is this html element with id "config" supposed to come from ? 


here is my current config:

```
// meteor-client.config.json
{
    "run-time": {
        "meteorEnv": {},
        "DDP_DEFAULT_CONNECTION_URL": "http://localhost:3000"
    },
    "import": {
        "meteor-base@1.0.4": [
            "underscore",
            "meteor",
            "modules-runtime",
            "modules",
            "promise",
            "babel-runtime",
            "ecmascript-runtime",
            "ecmascript",
            "base64",
            "ejson",
            "jquery",
            "check",
            "random",
            "tracker",
            "retry",
            "id-map",
            "ordered-dict",
            "geojson-utils",
            "diff-sequence",
            "mongo-id",
            "minimongo",
            "ddp-common",
            "ddp-client",
            "ddp",
            "allow-deny",
            "reactive-var",
            "mongo"
        ],
        "npm-bcrypt": [],
        "accounts-base": [
            "callback-hook",
            "localstorage",
            "accounts-base",
            "service-configuration",
            "underscore",
            "meteor-runtime-config",
            "meteor",
            "modules-runtime",
            "modules",
            "promise",
            "babel-runtime",
            "ecmascript-runtime",
            "ecmascript",
            "base64",
            "ejson",
            "jquery",
            "check",
            "random",
            "tracker",
            "retry",
            "id-map",
            "ordered-dict",
            "geojson-utils",
            "diff-sequence",
            "mongo-id",
            "minimongo",
            "ddp-common",
            "ddp-client",
            "ddp",
            "allow-deny",
            "mongo",
            "localstorage",
            "accounts-base",
            "npm-bcrypt",
            "sha",
            "srp",
            "url",
            "reload",
            "accounts-password",
            "oauth",
            "accounts-oauth",
            "oauth2",
            "observe-sequence",
            "htmljs",
            "blaze",
            "spacebars",
            "templating-runtime",
            "facebook",
            "accounts-facebook",
            "google",
            "accounts-google",
            "oauth/end_of_popup_response",
            "oauth/end_of_redirect_response"
        ],
        "accounts-facebook": [],
        "accounts-google": []
    },
    "export": {
        "accounts-base": [
            "Accounts"
        ],
        "ddp": [
            "DDP"
        ],
        "meteor": [
            "Meteor"
        ],
        "mongo": [
            "Mongo"
        ],
        "tracker": [
            "Tracker"
        ],
        "underscore": [
            "_"
        ]
    }
}
```
I added everything to accounts-base, which seems to work.

**Comment by DAB0mB** [comment]
@AwsmOli I just made some changes where you don't have to specify package dependencies, which will make stuff much clearer and more predictable. I believe we will release a new version very soon, and then I will let you know what you can do.

**Comment by Urigo** [comment]
released.
@AwsmOli can you please try the new version and if everything works and clear close the issue?
If you see that some things can be added to the docs, the best way to change that is to PR :)
thank you!

**Comment by AwsmOli** [comment]
Nice just tried it with specifying the source project and with a config just specifying the DDP Url, and it works like a charm (which is automagicly)!

`$ meteor-client bundle -s api`

```
meteor-client.cofig.json

{
    "run-time": {
        "DDP_DEFAULT_CONNECTION_URL": "http://localhost:3000"
    }
}
```
Its that easy now
Thanks guys!

**Comment by DAB0mB** [comment]
@AwsmOli I've just updated the tutorial with the new version. Further than that, you don't even need a config anymore, you can change the url by specifying the `--url` option.

**Comment by mordka** [comment]
As far as I understand we don't need to specify package in the config now. But I have local only package (packages/meteor-slingshot)  which is breaking the build.
``` 

=> Errors while initializing project:         
                                              
While selecting package versions:
error: unknown package in top-level dependencies: mordka:slingshot
```

I tried setting `PACKAGE_DIRS` variable but no luck

**Comment by DAB0mB** [comment]
@mordka Iteresting point, when I built the package I didn't consider a case where someone would like to bundle a client with local package. I will definitely check that. Can you please a new issue and copy your comment? This way I can track your issue more easily and I will give you a status on that.

**Comment by sqeeswy** [comment]
Hi guys I've got the same issue as @mordka, I provided solution proposal in PR #7. @DAB0mB could you check it out and decide if it's worth merging? Sorry for no tests, btw those provided in repo didn't work for me.
