### ISSUE TITLE
Configure server connection parameters programmatically?

### ISSUE THREAD

**Issue by KeithGillette** [Urigo/meteor-client-bundler#21]
I know that `meteor-client-bundler` allows one to specify the Meteor server URL via the `--url` command line flag at build time. Is there any way to have the client set its connection parameters programmatically by passing a configuration object similar to the approach taken by [`nativescript-meteor-client`](https://github.com/ntrp/nativescript-meteor-client)?

**Comment by DAB0mB** [comment]
@KeithGillette this feature is not yet available, but as a workaround, before you import `meteor-client` try setting your DDP configuration accordingly:

```js
(() => {
  const config = {
    "meteorEnv": {},
    "DDP_DEFAULT_CONNECTION_URL": "http://localhost:3000" // Or whatever you want
  };

  Object.defineProperty(window, '__meteor_runtime_config__', {
    get: () => config,
    set: Function()
  };
})();

require('meteor-client');
```

There are some several stuff I need to fix, I will do this once I have free time.

**Comment by KeithGillette** [comment]
Thanks for the work-around, @DAB0mB. I attempted to implement it in my Angular-Meteor project using TypeScript. I verified that a `__meteor_runtime_config__` object with the correct URL was created on `window` with the following code:

```typescript
import { environment } from './environments/environment';

const meteorClientConfig = {
	'meteorEnv': {},
	'DDP_DEFAULT_CONNECTION_URL': environment.serverUrlBrowser
};
Object.defineProperty(window, '__meteor_runtime_config__', {
	get: (): any => meteorClientConfig,
	set: (): void => {}
});
import 'meteor-client';
```

However, the imported `meteor-client` still seems to use its default settings when attempting to connect via DDP, as in the browser console I get repeated errors of the form:

`zone.js:1980 GET http://localhost:3000/sockjs/info?cb=dwbup308mq net::ERR_CONNECTION_REFUSED`

**Comment by megaslimegod** [comment]
KeithGillette, have you had any luck with a work around here?

**Comment by megaslimegod** [comment]
I have a solution!!!  The reason your solution doesn't work is because webpack changes the order of the code, and moves the imports before the const meteorClientConfig definition.

But the environment.ts is in-lined BEFORE this code!!!

So, if you put that code in the environment files, which makes plenty of sense, then you are sorted.  The --environment= now works.  Yes!!

**Comment by KeithGillette** [comment]
Thanks for figuring that out, @megaslimegod! This method for dynamically configuring such very basic parameters is more than a bit kludgy, but it does work!
