### ISSUE TITLE
meteor-client.js won't run in React Native

### ISSUE THREAD

**Issue by kokokenada** [Urigo/meteor-client-bundler#22]
Using v0.2.1 of meteor-client-bundler, I generated a meteor-client.js file with the following config:
````
{
  "runtime": {
    "DDP_DEFAULT_CONNECTION_URL": "http://localhost:3000"
  },
  "import": [
    "meteor-base@1.0.4",
    "accounts-password@1.3.5",
    "jalik:ufs@0.7.1_1",
    "jalik:ufs-gridfs@0.1.4"
  ]
}
````
When React Native loading the library it complains about various document and window references.   if you search the generated .js file it has 140 references to "document" and 59 references to "window".  I tried working around the problem by adding:
````
var document = {
  readyState: true,
  attachEvent: function() {},
  getElementsByTagName: function() {}
};
var window = {
  attachEvent: function() {}
}
````
to the top of the generated file which moved things along a little further, but there is a lot going on and it really seems to want the DOM.

My package.json dependencies are:
````
  "dependencies": {
    "meteor-node-stubs": "^0.2.6",
    "react": "16.0.0-alpha.6",
    "react-addons-pure-render-mixin": "^15.5.2",
    "react-meteor-data": "^0.2.10",
    "react-native": "0.44.0",
    "react-navigation": "^1.0.0-beta.9",
    "redux": "^3.6.0",
    "redux-observable": "^0.14.1",
    "rxjs": "5.2.0"
  },
````

**Comment by DAB0mB** [comment]
@kokokenada You don't seem to use the `meteor-native-packages` module. See [reference](https://github.com/Urigo/meteor-native-packages). This is basically a fork of Meteor's core packages with several modifications that will make your application run with React Native.

**Comment by kokokenada** [comment]
Right.  Thanks for the pointer.  How do I get the bundler to see the the native packages.  Where is the best documentation for the process?
