### ISSUE TITLE
You need 2 servers to run this?

### ISSUE THREAD

**Issue by gitTerebi** [Urigo/meteor-client-bundler#27]
Let me check...

So you need a meteor server to act as the DDP server?
Then if you are using webpack, you need to use that to spin up a server to host the client files? 
(It just so happens that you have a pre-bundled meteor-bundle.js that allows you to make minimongo calls etc?)

**Comment by lawrentiy** [comment]
You can put bundled client script to any server you want:
1. CDN
2. separated server
3. the same server or actually put it to the meteor app folder and deploy as you have deployed meteor app before
4. etc.

**Comment by Urigo** [comment]
thanks @lawrentiy
