### ISSUE TITLE
Integration Example with angular CLI ?

### ISSUE THREAD

**Issue by krishnapsms** [Urigo/meteor-client-bundler#33]
I want integrate MCB with my angular CLI project, so here am looking for clean approach to integrate MCB with up and running. Guide me further, if any examples are existing or working on it ?

**Comment by krishnapsms** [comment]
@Urigo I've been go through the [Whatsapp clone tutorial](https://angular-meteor.com/tutorials/whatsapp2-tutorial) to replicate same with angular CLI, there i got two version to get started which one i will prefer either starting with Ionic CLI or Meteor CLI ?

**Comment by Urigo** [comment]
The Ionic CLI.
We just deployed a new, updated version of this tutorial yesterday so check it out.
(Ionic CLI is very similar to the Angular CLI in the way you should integrate it with Meteor)

**Comment by krishnapsms** [comment]
Thanks for getting back to me sure i will check it out and also we are looking forward to get simple todo app tutorial with Angular CLI for direct approach with it.

**Comment by krishnapsms** [comment]
@Urigo Hi, I've been started integrating Angular CLI with Meteor by following that Ionic CLI tutorial there i've following doubts
- Angular CLI is coming up with Webpack whether we need to consider that again for configurations
- While integrating with meteor server am not able to get collection from meteor in Angular CLI it says cannot find the module while `import { Quizzes } from 'api/collections';` Have no clear idea where this comes from how it get importing it.

**Comment by yonsterTheMonster** [comment]
@krishnapsms Hi, can you upload your repo so i can help you i'm also struggling with it.

**Comment by krishnapsms** [comment]
Hi @yonsterTheMonster refer this issue l[ink](https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/82#issuecomment-310415744)

**Comment by krishnapsms** [comment]
Hi @Urigo Should i have to eject webpack config and then configure it with angular CLI ? Is it proper way or else any other possibility to configure in .angular-cli.json ?

**Comment by michaelb-01** [comment]
I'm trying the same thing, is there a good solution yet?

**Comment by SheshoVega** [comment]
someone has achieved satisfactory integration?

**Comment by darkbasic** [comment]
I made a small [AngularCLI+Meteor-client-bundler tutorial](https://github.com/darkbasic/angularcli-meteor) where I ported most of the content from the first 4 chapters of the IonicCLI tutorial. Can you please close this bug report?

**Comment by TheAppchemist** [comment]
@darkbasic Thanks I tried it out it works. Only problem is that I can a /src/app/services/user-service.ts (13,22): Cannot find name 'Profile'

Profile is a model in api/models/profile.ts

Do you know what the problem could be. I've been struggling with this for 2 days now.

**Comment by darkbasic** [comment]
Please share a repository showing the issue. I'm closing this.
