### ISSUE TITLE
Not working with Meteor 1.5.1

### ISSUE THREAD

**Issue by carlos-olivera** [Urigo/meteor-client-bundler#34]
Hi!

I am working with this package for a fitness app (ionic) project.

I updated to Meteor 1.5.1 and got a bug: [https://github.com/meteor/meteor/issues/8902](https://github.com/meteor/meteor/issues/8902)

I had to modify the code in order to specify a meteor version when the script create the temp meteor app.

I can create a PR if you need a hand with that.

Carlos.

**Comment by mvandenbrink** [comment]
I had a similar issue. I had meteor 1.5 installed, but after the meteor-client-bundler run I encountered an error. 

Uncaught TypeError: Cannot read property 'get' of undefined in polyfill:3

I updated meteor to 1.5.1, removed node_modules/*, did a clean install with npm install and the meteor-client-bundler. After these steps everything was working again.

**Comment by carlos-olivera** [comment]
I've not tried to clean node modules.

I forced meteor-client-bundler to use 1.5.1.

**Comment by Slavrix** [comment]
The clean install after upgrading to meteor 1.5.1 worked for me also.

**Comment by ingleo** [comment]
Hi @carlos-olivera I'm trying to run the meteor client bundler with 1.4.4.3 meteor version, can you tell me please, how I can to modify the code to  do that?
Really appreciate your help, regards

**Comment by DAB0mB** [comment]
@carlos-olivera I've just released a new version of `meteor-client-bundler`, this issue should be fixed. For now I'm closing this issue, but if you can confirm it, that would be great!
