### ISSUE TITLE
Meteor.userId() missing

### ISSUE THREAD

**Issue by rokanost** [Urigo/meteor-client-bundler#35]
Everything works well, but I can't get Meteor.userId()
Any ideas?

Thanks

**Comment by rokanost** [comment]
It's not available globally, had to use "import" inside file.

**Comment by robatswitchcraft** [comment]
Have you imported "meteor-client" somewhere.

e.g. in main.ts add

import 'meteor-client';

**Comment by rokanost** [comment]
I did, everything else is working fine except this.

**Comment by robatswitchcraft** [comment]
We will need a few more clues.  Sounds like Meteor class is not in global scope.

I've added this to my .angular-cli.json
"scripts": [
  "../node_modules/meteor-client.js"
],
(and meteor-client script is there).

And import is in first line of main.ts.

**Comment by rokanost** [comment]
Hmm, when i built the bundle, i havent specified the source option, as i
did in the other meteor project folder and then moved the generated js file
to other ionic project. I also store this bundle file inside src folder, i
should try moving it to node_modules probably

thanks

**Comment by rokanost** [comment]
New error now:
__WEBPACK_IMPORTED_MODULE_4_meteor_meteor__.Meteor.user is not a function

**Comment by rokanost** [comment]
I've figured it out, looks like my bundle is missing bunch of stuff
