### ISSUE TITLE
disable underscore from global scope

### ISSUE THREAD

**Issue by msio777** [Urigo/meteor-client-bundler#4]
Hi,
Old version included export property. I' ve never tried it on my own. I 'd expect something in the current version too. I don't want to use underscore on frontend and underscore is in global scope included. Is there any chance to resolve this ? I'm using angular 2 in my project 
Thanks 
Michal

**Comment by DAB0mB** [comment]
@msio777 Unfortunately you can't. `underscore` is a native part of Meteor's implementation, so without it, Meteor will break. Personally I'd also be happy to get rid of it and replace it with `lodash`, but it's not guaranteed to work properly. Hopefully you got your answer, I'm closing this issue :-)

**Comment by msio777** [comment]
Thanks but if I assign lodash to another constant like `import * as lodash from 'lodash'` that is ok isn't ?

**Comment by DAB0mB** [comment]
@msio777 It's ok, but then you'll have to load both `underscore` and `lodash` which are pretty identical. It will make the script file unnecessarily bigger, and the requests slower. I wouldn't have done that personally.

**Comment by msio777** [comment]
yeah I thought of that but I building cordova project and current version of underscore is 1.5.2 and I  need e.g. _.mapObject() and that's included only in higher versions.

**Comment by DAB0mB** [comment]
@msio777 You should try looking for a solution on StackOverflow, there's a very big community in there and I bet they will give you the best solution possible.

**Comment by msio777** [comment]
thanks :)
