### ISSUE TITLE
Execute meteor-client:bundle whit specific version

### ISSUE THREAD

**Issue by fernandoarevalo** [Urigo/meteor-client-bundler#40]
Hi everyone!

Everytime when I try to execute meteor-client:bundle whit 1.4.4_3 version, it starts to update to current meteor version (1.5.1), how i can to execute it for 1.4.4.3 version?

Regards.

**Comment by romiohasan** [comment]
My ionic app and web app is on meteor-1.5 and the build tool is trying to update to 1.5.1. But after downloading, it just keeps hanging on "Extracting meteor-tool@1.5.1..."  for hours.
Tried running several times for hours but not completing the process.
**on Windows-10 with meteor 1.5.

**Comment by blackjack0v0** [comment]
@romiohasan  you can download the sourcecode from https://meteorinstall-4168.kxcdn.com/packages-bootstrap/1.5.1/meteor-bootstrap-os.linux.x86_64.tar.gz
and unzip the 1.5.1 tool  to your dir  .meteor/  in the root(or maybe in c:// on win10, )
![2017-08-20 21-43-13](https://user-images.githubusercontent.com/27153331/29495386-c1e24e9e-85f0-11e7-90d7-b8a2ecbfeea7.png)

**Comment by romiohasan** [comment]
@blackjack0v0 Thanks.
I have already solved it in another way. I cleaned everything, removed the npm package and reinstalled meteor.
Then I again installed meteor-client:bundle from npm and this time I was looking into this directory for unzip/extraction process completion: 
**C:\Users\myusername\AppData\Local\.meteor\packages\meteor-tool**

**It took about 90+ minutes to complete the extraction process on my SSD hard-disk with 8GB Ram (Win10)**.

**Comment by DAB0mB** [comment]
@fernandoarevalo Use the `--release` option. For more information, see the `README.md` file
