### ISSUE TITLE
Run command (meteor-client:bundle) raises an error (spawnSync meteor ENOENT)

### ISSUE THREAD

**Issue by vv001** [Urigo/meteor-client-bundler#52]
Hello,

After performing an ‘npm install’ and downloading additional necessary packages I try to run my project locally with the following command: npm run meteor-client:bundle (on mac os high sierra)

This executes the following in my config:
“meteor-client:bundle”: “meteor-client bundle -s api -c meteor-client.config.json --url http://192.168.0.4:3000”

It keeps returning the following error:

OrderClient@0.0.1 meteor-client:bundle /Users/vl01/orderapp
meteor-client bundle -s api -c meteor-client.config.json --url http://192.168.0.4:3000
/usr/local/lib/node_modules/meteor-client-bundler/node_modules/execa/index.js:277
throw (result.error || new Error(result.stderr === ‘’ ? result.stdout : result.stderr));
^

Error: spawnSync meteor ENOENT
at _errnoException (util.js:1024:11)
at Object.spawnSync (child_process.js:579:20)
at Function.module.exports.sync (/usr/local/lib/node_modules/meteor-client-bundler/node_modules/execa/index.js:274:30)
at Object.bundle (/usr/local/lib/node_modules/meteor-client-bundler/lib/bundler.js:45:23)
at Command. (/usr/local/lib/node_modules/meteor-client-bundler/cli:47:13)
at Command.listener (/usr/local/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:315:8)
at emitTwo (events.js:126:13)
at Command.emit (events.js:214:7)
at Command.parseArgs (/usr/local/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:653:12)
at Command.parse (/usr/local/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:475:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! OrderClient@0.0.1 meteor-client:bundle: meteor-client bundle -s api -c meteor-client.config.json --url http://192.168.0.4:3000
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the OrderClient@0.0.1 meteor-client:bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I am kind of lost here what might be the issue.Tried npm run clean, npm clear cache, removed the node_modules and started from a clean slate, but it keeps happening.
I tried it with various versions of node and npm (node 8.9.3 and node 6.12 and node 9.3 etc), in all cases it keeps happening.

Does anyone know how it might be possible to resolve this issue or has run against this issue int he past? Your help would be much appreciated. Thanks in advance

**Comment by vv001** [comment]
We were able to finally resolve it. The issue was that we were missing some symlinks to the right directory (containing the meteor files), in order to make the meteor bundle build/run.

**Comment by Urigo** [comment]
thank you @vv001 for the info.
Can you give an example of those symlinks so others can benefit from it?
thanks

**Comment by vv001** [comment]
Hello Uri, the symlink was to the meteor server files, which we use to bundle the client with. Creating a symlink and than running the bundler resolved this issue.
