### ISSUE TITLE
Fails with Meteor 1.6.1

### ISSUE THREAD

**Issue by robport** [Urigo/meteor-client-bundler#54]
There are two issues with running the bundler against Meteor 1.6.1.  This results in you getting a "Meteor is not defined" error in the console.  

1. In the build of 1.6.1, the global-imports.js file moved has moved directories, hence the bundler is not including it in the meteor-client.js
2. The _OnMigrate method has been removed from Meteor.  You should use Reload._onMigrate instead.

Fixes; 
1. In bundler.js change the filter to pick up the missing file; ie.

    .filter(function (pack) {
      return (pack.where === "client" &&
          pack.type === "js" &&
          Path.dirname(pack.path) === "packages")
          || pack.path.indexOf('global-imports') > -1
    })

2. Change the post-bundle.js to;

if (Package.reload) {
  Reload._onMigrate(function () {
    return [false];
  });
}

I would push these changes up to the repo in a PR, but I don't have access.

**Comment by afaur** [comment]
@robport I tested your changes and they worked great.

To be able to submit a PR to a branch that you do not have access to you can follow these steps...
- Fork the repository (it will make robport/meteor-client-bundler a repo that you have access to)
- Clone the repository locally
- Make the desired changes
- Run `git add -A`
- Run `git checkout -b fix-issue-<number>`
- Run `git commit -m 'Fixes #<number'
- Run `git push`
- Visit `http://github.com/robport/meteor-client-bundler`
- Click *branches* then click *new pull request* next to fix-issue-<number>
- Add any notes to the pull request and then submit it
  - By default it is made against the repository you originally forked from
- Once approved it will add your changes into the repo you do not have access to

As an example I did this for your issue.
Which you should see above this comment.

If you decide to follow these steps and submit a PR with your changes I will gladly close mine. 

If not, I added credit to you in the pull request message and commit message.

**Comment by robport** [comment]
@afaur please go ahead and merge your PR.  Thanks for the credit.  

Regards,
Rob

**Comment by afaur** [comment]
@robport It will be up to the maintainer to merge the changes. 
Thanks for your fix on this it helped me out.

**Comment by robport** [comment]
Ah, gotcha.  I'll know what to do next time.

**Comment by stefanholzapfel** [comment]
I can confirm that the fix works, thank you!

@Urigo Uri can you please merge them in when you have spare minute? Thanks!

**Comment by Urigo** [comment]
thank you everyone for the fix and the testing!
just merged and released version `0.4.0`.
Please let me know if that works for you.
Sorry for the late response from me

**Comment by stefanholzapfel** [comment]
@Urigo Works like a charm, thanks!
