### ISSUE TITLE
bundler config imports ignored

### ISSUE THREAD

**Issue by Slavrix** [Urigo/meteor-client-bundler#56]
`{
  "runtime": {
    "DDP_DEFAULT_CONNECTION_URL": "https:/adadadadadadadadadadad.com.au"
  },
  "import": [
    "meteor-base",
    "mongo",
    "reactive-var",
    "jquery",
    "tracker",
    "standard-minifier-css",
    "abernix:standard-minifier-js",
    "es5-shim",
    "ecmascript",
    "shell-server",
    "accounts-base",
    "slavrix:account-password-dupeemail",
    "alanning:roles"
  ]
}`

this is my bundler config file, however, when i run the command to create the bundle, it still adds app of the packages that are in my meteor package.
eg angular-compilers etc.

'meteor-client bundle -s api -c bundler.config.json'
is the cmd in running

i get these errors when i use the meteor-client and i believe they are due to the angular-compilers packages adding unneeded code to the bundle (as the meteor client should be ignored for this bundle creation)
meteor-client.js:58946 GET http://localhost:8102/3584702a176a0275787f6fec51aa85112418c25d.css?meteor_css_resource=true net::ERR_ABORTED

meteor-client.js:58946 GET http://localhost:8102/0cf1cb52d27002ebd53afda3c3cc734cb2f3b2eb.css?meteor_css_resource=true net::ERR_ABORTED

**Comment by Slavrix** [comment]
if i remove the angular-compilers package first, then i still get the messages of those missing css files.
any thoughts on what might be causing it?
these are all my packages

meteor-base
mongo
reactive-var
jquery
tracker
standard-minifier-css 
es5-shim
shell-server
accounts-base
npm-bcrypt
reywood:publish-composite
http
alanning:roles
check
email
ecmascript
angular-compilers
abernix:standard-minifier-js
slavrix:account-password-dupeemail

but the fact that the config files import doesnt work prevents me from ignoring any packages, short of uninstalling them then adding them again

**Comment by impcyber** [comment]
Looking at the code https://github.com/Urigo/meteor-client-bundler/blob/master/lib/bundler.js#L84
--config not used if --source defined
