### ISSUE TITLE
ReferenceError: __meteor_runtime_config__ is not defined

### ISSUE THREAD

**Issue by hayk94** [Urigo/meteor-client-bundler#57]
I am trying to use this with my webpack project

but I get this error

`ReferenceError: __meteor_runtime_config__ is not defined`

Here are the steps I did

create a new meteor project

then I run the client bundler like this

`meteor-client bundle —source=./ —destination=./meteor-client.bundle.js —config=meteor-client.config.json`

and here is the config

    {
      "runtime": {
        "DDP_DEFAULT_CONNECTION_URL": "http://localhost:3000"
      },
      "import": [
        "meteor-base@1.3.0",
        "mongo@1.4.2",
        "reactive-var@1.0.11",
        "jquery@1.11.10",
        "tracker@1.1.3",
        "shell-server@0.3.1",
        "react-meteor-data"
      ]
    }

then I copy my `meteor-client.js` to my webpack project `node_modules`

and import it like this

`import 'meteor-client'`

then I bundle webpack and run dev-server and I get the above mentioned error.

**Comment by Urigo** [comment]
please try again with the new `0.4.0` version
