### ISSUE TITLE
How sign in/up with Facebook

### ISSUE THREAD

**Issue by katusiky** [Urigo/meteor-client-bundler#58]
I have 3 app.

Meteor = api.example.com
Web = example.com
Mobile = mobile.example.com

How do I configure XX to redirect to WEB or MOBILE as the case may be?

i follow https://angular-meteor.com/tutorials/whatsapp2/ionic/facebook but i cant setup to 3 diferents subdomains.

Thanks.

**Comment by ardatan** [comment]
See #77

**Comment by katusiky** [comment]
@ardatan  this dont work for me example.

@Urigo  can u help me please?

Thanks

**Comment by ardatan** [comment]
@katusiky Can you give more details?

**Comment by katusiky** [comment]
@ardatan I need login with facebook from my client.

when i try login from client, facebook automatically redirect to server subdomain and never redirect again to client. 

i cant create nginx config to 3 differents subdomains.
