### ISSUE TITLE
Unknown package in top-level dependencies

### ISSUE THREAD

**Issue by sqeeswy** [Urigo/meteor-client-bundler#6]
While using source option (-s) with existing meteor project containing custom packages in packages/ directory, we're getting following error:

```
While selecting package versions:
error: unknown package in top-level dependencies: custom:package-name
```

Can source option be extended to load also those custom packages from package directory?

**Comment by sqeeswy** [comment]
CR proposal for this issue in #7

**Comment by DAB0mB** [comment]
I've just merged my own PR. Closing this issue
