### ISSUE TITLE
"document.createElement is not a function" When Used With React Native

### ISSUE THREAD

**Issue by gchallen** [Urigo/meteor-client-bundler#60]
I'm following something like the example integration with React Native but encountering the following problem right after the device connects:

````
Exception in queued task TypeError: document.createElement is not a function
    at storage.native.js:67
    at Array.forEach (<anonymous>)
    at Object.checkNewVersionDocument (storage.native.js:65)
    at _CachingChangeObserver.added (meteor-client.js:12489)
    at Object.added (meteor-client.js:11963)
    at meteor-client.js:11082
    at Meteor._SynchronousQueue.SQp.runTask (meteor-client.js:1113)
    at Meteor._SynchronousQueue.SQp.flush (meteor-client.js:1154)
    at Meteor._SynchronousQueue.SQp.drain (meteor-client.js:1168)
    at Cursor.observeChanges (meteor-client.js:10941)
````
Note that the line numbers appear to be incorrect, but the error seems to being generated by this code in the generated bundle:

````javascript
if (doc._id === 'version-refreshable' && doc.version !== autoupdateVersionRefreshable) {
  autoupdateVersionRefreshable = doc.version; // Switch out old css links for the new css links. Inspired by:
  // https://github.com/guard/guard-livereload/blob/master/js/livereload.js#L710
  ...
  if (newCss.length !== 0) {
    newCss.forEach(function (css) {
    var newLink = document.createElement("link");
    ...
````

I'm not a Meteor expert but it seems that the server is pushing some document with a special ID that is causing the client to try and update page CSS, which fails given that there is no DOM to manipulate.

Removing this entire case solves the problem, but of course it now requires a separate step each time the bundle is rebuilt. No idea what the right solution is here...? Note that this seems related to #9, although it's going down a slightly different code path so the fix is probably different...

**Comment by ardatan** [comment]
How could you produce this issue?
And could you please update `react-native-meteor-polyfills` to 1.0.6?

**Comment by maximtmartin** [comment]
Any idea how to fix this problem?

I'm using: 
"react-native-meteor-polyfills": "1.0.9",
"react-native": "0.57.2",
