### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [Urigo/meteor-client-bundler#65]
i installed this module in a angular-cli generated project following the README and this link https://medium.com/@ardatan/angular-cli-meteor-no-more-eject-webpack-configuration-4e718aa855b6

and when I try to bundle `./node_modules/.bin/meteor-client bundle -s api` I get that error `env: node\r: No such file or directory`.

There are similar issues on other repos like this one https://github.com/JohnPostlethwait/fixme/issues/22

OS: macOS 10.13.6

**Comment by ardatan** [comment]
Thank you for your collaboration, but it is not related to this package as you said!
