### ISSUE TITLE
google's search/indexer bot

### ISSUE THREAD

**Issue by portah** [Urigo/meteor-client-bundler#76]
I've switched one of my web sites to meteor-client-bundler, everything works as expected. However, recently I found out that google's search console can't render my page.  Based on this info https://www.youtube.com/watch?v=fiT5g9KSxmw, https://developers.google.com/search/docs/guides/rendering - I added required polyfills, didn't help. Then I downloaded google chrome build 41.xxx and I tried to open my page.

I've got tons of "Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode", in  meteor-client.js ( the first one at meteor-client.js:5859). The solution is to add "use strict"; but it is a lot.

Also some syntax like ```const {varName=false} = _a_variable``` also not supported by google chrome 41. 

The strange part, in other project which is almost the same, where I use angular-compilers meteor package and do 'meteor build', google search engine can render the page.

**Comment by portah** [comment]
Few updates on this.

1. For angular related polyfills and addons I used angular.io code https://github.com/angular/angular/tree/master/aio/
2. To generate meteor-client.js that compatible with old google chrome. In 'meteor-client.config.json' npm package has to be added ```"npmPackages": [ "babel-preset-env" ]```. Also, 'bundler.js' has to be changed, have added 'presets: [ "env" ]' to Babel.transform:

```
packContent = Babel.transform(packContent, {
          ast: false,
          comments: true,
          compact: false,
          filename: packFile,
          plugins: [EscapeCommonJSPlugin],
          presets: [ "env" ],
          sourceType: "script"
        }).code;
```

So, If it is possible to move ```presets: [ "env" ]``` into config file would be great. Then next step would be to use one config/client for old browsers and the other for latest.

Google search console rendered the page I'll see how indexing works.

**Comment by ardatan** [comment]
You can set `arch` to `web.browser.legacy` in your meteor-client-bundler configuration, so you can get compatible client bundle.

**Comment by portah** [comment]
@ardatan I did not know, about that, thank you. I'll definitely try it

**Comment by portah** [comment]
I believe that worked
