### ISSUE TITLE
Facebook login

### ISSUE THREAD

**Issue by katusiky** [Urigo/meteor-client-bundler#77]
How i can login with facebook ? My setup is angular 5 in firebase hosting as www.xxxxx.com and my meteor backend in AWS elastic beanstalk as api.xxxxx.com

**Comment by ardatan** [comment]
You can see Meteor's documentation about Facebook login.
https://guide.meteor.com/accounts.html#oauth-logging-in

**Comment by katusiky** [comment]
@ardatan  this dont work for me example.

@Urigo can u help me please?

Thanks

**Comment by Urigo** [comment]
@katusiky can you please create a reproduction on Github and share it here?
