### ISSUE TITLE
setTimeout Warnings, Data Consistency Crashes When Using React Native

### ISSUE THREAD

**Issue by gchallen** [Urigo/meteor-client-bundler#82]
I've integrated a bundle built into this tool into a React Native application. Unfortunately, I've encountered a few problems that are showstoppers for us. So at this point I'm trying to decide whether to give up on getting Meteor to work and try GraphQL or keep trying.

The first problem is that Meteor tries to set long timers, which immediately trigger Yellow Box warnings when using React Native. It seems like the a heartbeat is trying to be set for a period of multiple minutes, which React Native complains about. I've silenced those for now but I'm concerned that this will prevent other things from working properly.

Second, and more problematic, is that Meteor crashes my app regularly when it's in the background. This is a proximity tracking app, so it needs to run continuously. But periodically I get errors like this:

```
com.facebook.react.common.JavascriptException: Expected to find a document already present for removed
```
Or sometimes the error says that expected to not find a document when adding, or to find one when making changes. Anyway, it seems like there is some problem with data synchronization—but it doesn't pop up regularly enough for me to debug effectively. I ran a stress test overnight and things worked fine, so I'm starting to suspect that it may be due to network disconnections or changes occurring because of mobility.

Anyway, at this point it seeming that being able to reliably run for hours and days at a time handling multiple client reconnections and the other weirdnesses caused by network transitions just might be a bit out of scope for Meteor. I'm curious though if anyone else has experienced similar issues or has ideas for a workaround?

**Comment by ardatan** [comment]
You can see that this is not directly related to meteor-client-bundler. This warning or issue whatever you call it is caused because of the way Meteor handles real-time connection between client and server.
