### ISSUE TITLE
after meteor build, why put all package into a big meteor-client.js?

### ISSUE THREAD

**Issue by fangjj** [Urigo/meteor-client-bundler#86]
use config web.browser.legacy build meteor-client.js is too big, almost 2.5M. i don't know why put all packages in a javascript file. please explain it. thank you.

**Comment by fangjj** [comment]
@Urigo any help?

**Comment by ardatan** [comment]
You can add your configuration these settings to use node libraries externally;
```
"externalNpmPackages": [
      "@babel/runtime",
      "core-js",
      "meteor-node-stubs",
      "react"
  ],
  "generateNodeModules": true,
  "npmInstall": false
```
