### ISSUE TITLE
Error: Cannot find module 'react'

### ISSUE THREAD

**Issue by Phazeoner** [Urigo/meteor-client-bundler#95]
Hi
For the first time everything worked. I added a new dependency and run mcb again, now have this error. What should I do?
![2018-12-06 11 05 16](https://user-images.githubusercontent.com/28909288/49571911-9a379f00-f94b-11e8-8eaf-5ff411486772.png)

My config 

` "import": [
    "meteor-base",
    "mongo",
    "cfs:standard-packages",
    "cfs:gridfs",
    "react-meteor-data"
  ],
  "externalNpmPackages": [
    "core-js",
    "@babel/runtime",
    "meteor-node-stubs",
    "react"
  ],`

**Comment by ardatan** [comment]
Do you have react installed on the project you’re running the client bundle?

**Comment by Phazeoner** [comment]
Yes

`"dependencies": {
    "@babel/runtime": "7.0.0-beta.51",
    "meteor-client-bundler": "^0.6.0",
    "meteor-node-stubs": "^0.4.1",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-router": "^4.3.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "mcb": "meteor-client bundle --config=meteor-client.config.json"
  }`

**Comment by Phazeoner** [comment]
I created a new project and the same error 😕

https://github.com/Phazeoner/meteor-client-bundler-test

**Comment by charpeni** [comment]
> "import": [ "meteor-base", "mongo", "cfs:standard-packages", "cfs:gridfs", "react-meteor-data" ], "npmPackages": [ "core-js", "@babel/runtime", "meteor-node-stubs", "react" ],
> try this，change externalNpmPackages to npmPackages

It doesn't work.

Looks like something change about module requires in Meteor 1.8:

> The reify npm package has been updated to version 0.17.3, which introduces the `module.link(id, {...})` runtime method as a replacement for `module.watch(require(id), {...})`. Note: in future versions of `reify` and Meteor, the `module.watch` runtime API will be removed, but for now it still exists (and is used to implement `module.link`), so that existing code will continue to work without recompilation.

@ardatan Do you have any ideas?

**Comment by fangjj** [comment]
"import": [ "meteor-base", "mongo", "cfs:standard-packages", "cfs:gridfs", "react-meteor-data" ], "npmPackages": [ "core-js", "@babel/runtime", "meteor-node-stubs", "react" ],"npmInstall": true,

**Comment by Phazeoner** [comment]
It works! Thanks for your help 👍

**Comment by bharath2212** [comment]
I don't know where I add this code?
